version: "3.9"
services:
  postgres-proxy:
    image: postgres:14.1-alpine
    container_name: postgres-proxy
    restart: always
    environment:
      POSTGRES_DB: "proxy"
      POSTGRES_USER: "dimad"
      POSTGRES_PASSWORD: "F27gk9LeN"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "65432:5432"
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data:delegated
  
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "16379:6379"
    volumes:
      - /var/data/redis/data:/data:delegated

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: doroshenko@tutanota.com
      PGADMIN_DEFAULT_PASSWORD: F27gk9LeN
    ports:
      - "5050:80"
      - "5443:443"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G