Database:
  host: "127.0.0.1"
  port: 65432
  user: "dimad"
  password: "F27gk9LeN"

App:
  host: '0.0.0.0'
  port: 7890
  superuser: "dimad"
  password: "F27gk9LeN"

Redis:
  host: '127.0.0.1'
  port: 16379
  db: 0